language: php
php:
  - '7.1'
  - nightly

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - composer test

after_success:
    - bash <(curl -s https://codecov.io/bash)